name: Cloudflare Cleanup

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every week on Sunday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install

      - name: Clean Cloudflare Deployments (one-among-us)
        run: yarn cloudflare_clean
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_PAGES_PROJECT_NAME: one-among-us

      - name: Clean Cloudflare Deployments (our-data)
        run: yarn cloudflare_clean
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CF_PAGES_PROJECT_NAME: our-data
